# Generated by Django 5.2.6 on 2025-10-16 19:39

import apps.dashboard.models
import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtemeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(editable=False, max_length=128)),
                ('ateme_id', models.CharField(editable=False, max_length=128, null=True)),
                ('payload', models.JSONField(default=dict, editable=False)),
                ('state', models.CharField(default='created', max_length=16)),
                ('priority', models.SmallIntegerField(default=1)),
                ('output', models.FilePathField(match='.*.mpd$', null=True, path='/export/isilj/encode-ateme/output', recursive=True)),
                ('job_details', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Edgeware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('celery_id', models.CharField(max_length=255, null=True, unique=True)),
                ('ew_id', models.CharField(max_length=255, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('ftp_done', 'FTP UPLOADED'),
                            ('ftp_error', 'FTP ERROR'),
                            ('ew_error', 'EW ERROR'),
                            ('done', 'EW SUCCESS'),
                            ('ew_pending', 'EW PENDING'),
                            ('etl', 'Collected from log'),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ('encoder', models.CharField(choices=[('ateme', 'ATEME'), ('vidra', 'VIDRA')], default='ateme', max_length=5)),
                ('ftp_dir', models.CharField(default='', max_length=255)),
                ('ftp_cleaned', models.BooleanField(default=False)),
                ('msg', models.JSONField(default=dict)),
                ('title', models.CharField(max_length=255, null=True)),
                ('stream_url', models.CharField(max_length=255, null=True)),
                ('host', models.CharField(default='', max_length=32)),
                ('ingested', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_name', models.FilePathField(match='.*', path='/home/kamba/Videos/', recursive=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('md5', models.TextField(blank=True, null=True)),
                ('duration', models.BigIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('a_codec', models.TextField(blank=True, null=True)),
                ('v_codec', models.TextField(blank=True, null=True)),
                ('props', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('start', 'start'), ('success', 'success'), ('error', 'error')], default='success', max_length=10)),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                (
                    'name',
                    models.CharField(
                        choices=[('isilon-lj', 'Isilon LJ'), ('isilon-mb', 'Isilon MB'), ('atlas-01-vod-ftp', 'vod_images'), ('vod-images-ftp', 'vod_images')], default='isilon-lj', max_length=18
                    ),
                ),
                ('type', models.CharField(choices=[('streaming', 'streaming'), ('archive', 'archive'), ('vod_images', 'vod_images')], default='streaming', max_length=10)),
                ('link_prefix', models.CharField(blank=True, default='', max_length=128)),
                ('folder', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('hls', 'hls'), ('dash', 'dash'), ('mss', 'mss')], max_length=4)),
                ('uri', models.URLField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VidraJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('env', models.CharField(choices=[('stag', 'Staging'), ('prod', 'Production')], default='stag', max_length=4)),
                ('name', models.CharField(max_length=128)),
                ('uuid', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=16)),
                ('hostname', models.CharField(max_length=32)),
                ('runtime', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('args', models.JSONField()),
                ('kwargs', models.JSONField()),
                ('meta', models.JSONField(default=dict, null=True)),
                ('result', models.JSONField(null=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='AtemeJobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ateme_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('inerror', 'Failed'), ('running', 'Started'), ('completed', 'Success')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.atemejob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryUri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('hls', 'hls'), ('dash', 'dash'), ('mss', 'mss')], max_length=4)),
                ('uri', models.CharField(max_length=512)),
                ('ew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.edgeware')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField(unique=True)),
                ('entry_type', models.CharField(choices=[('dir', 'Directory'), ('file', 'File')], max_length=10)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboard.fileentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='atemejob',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.fileentry'),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('use_staging_db', models.BooleanField(default=True)),
                ('enable_drm', models.BooleanField(default=True)),
                ('default_active_tv', models.BooleanField(default=True)),
                ('default_active_web', models.BooleanField(default=True)),
                ('default_active_mobile', models.BooleanField(default=True)),
                ('default_active_lte', models.BooleanField(default=True)),
                ('catalog_name', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'logo',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])],
                    ),
                ),
                ('vidra_task', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('queue', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('provider_fs', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(editable=False, max_length=255)),
                ('delivery_time', models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    'status',
                    models.CharField(choices=[('upload', 'Delivered'), ('enqueued', 'Enqueued'), ('processing', 'Processing'), ('failed', 'Failed')], default='upload', editable=False, max_length=20),
                ),
                ('file', models.FilePathField(editable=False, match='.*', path='/export/isilj/fenix2', recursive=True, unique=True)),
                ('provider', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='dashboard.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
