# Generated by Django 5.2.6 on 2025-10-18 23:08

import apps.dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='storages',
            field=models.ManyToManyField(to='dashboard.storage'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
