# Generated by Django 5.2.6 on 2025-10-18 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_provider_storages_alter_provider_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='edge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.edgeware'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='file',
            field=models.FilePathField(match='.*tar', path='/export/isilj/fenix2', recursive=True, unique=True),
        ),
        migrations.DeleteModel(
            name='DeliveryUri',
        ),
    ]
