# Generated by Django 5.2.6 on 2025-10-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_stream_edge_alter_packet_file_delete_deliveryuri'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFile',
        ),
        migrations.AddField(
            model_name='vidrajob',
            name='worker',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vidrajob',
            name='args',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vidrajob',
            name='env',
            field=models.CharField(choices=[('stag', 'Staging'), ('prod', 'Production')], default='stag', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='vidrajob',
            name='hostname',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vidrajob',
            name='kwargs',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vidrajob',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vidrajob',
            name='state',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='vidrajob',
            name='uuid',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
