# Generated by Django 5.2.6 on 2025-10-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_mediafile_vidrajob_worker_alter_vidrajob_args_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidrajob',
            name='exception',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vidrajob',
            name='received',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vidrajob',
            name='started',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vidrajob',
            name='succeeded',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vidrajob',
            name='timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='vidrajob',
            name='runtime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
