# Generated by Django 5.2.6 on 2025-10-19 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_vidrajob_exception_vidrajob_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('celery_id', models.CharField(max_length=255, null=True, unique=True)),
                ('ew_id', models.CharField(max_length=255, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('ftp_done', 'FTP UPLOADED'),
                            ('ftp_error', 'FTP ERROR'),
                            ('ew_error', 'EW ERROR'),
                            ('ew_done', 'EW SUCCESS'),
                            ('ew_pending', 'EW PENDING'),
                            ('etl', 'Collected from log'),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ('encoder', models.CharField(choices=[('ateme', 'ATEME'), ('vidra', 'VIDRA')], default='ateme', max_length=5)),
                ('ftp_dir', models.CharField(default='', max_length=255)),
                ('ftp_cleaned', models.BooleanField(default=False)),
                ('msg', models.JSONField(default=dict)),
                ('dropped', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('stream_url', models.CharField(max_length=255, null=True)),
                ('host', models.CharField(default='', max_length=32)),
                ('ingested', models.DateTimeField(null=True)),
                ('flower', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.vidrajob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
