# Generated by Django 5.2.6 on 2025-10-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_logharvest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['user__username']},
        ),
        migrations.RemoveField(
            model_name='provider',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='name',
        ),
    ]
