# Generated by Django 5.2.6 on 2025-10-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_provider_options_remove_provider_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeware',
            name='content_duration_ms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='edgeware',
            name='playable',
            field=models.BooleanField(default=False),
        ),
    ]
