# Generated by Django 5.2.6 on 2025-10-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_edgeware_content_duration_ms_edgeware_playable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgeware',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='edgeware',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
