# Generated by Django 5.2.6 on 2025-10-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_edgeware_created_alter_edgeware_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edgeware',
            old_name='ftp_cleaned',
            new_name='api_loaded',
        ),
    ]
