# Generated by Django 5.2.6 on 2025-10-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_ftp_cleaned_edgeware_api_loaded'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('edge', 'type'), name='unq_edge_stream'),
        ),
    ]
