# Generated by Django 5.2.6 on 2025-10-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_stream_unq_edge_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeware',
            name='expired',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='edgeware',
            name='offer_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='edgeware',
            name='ingested',
            field=models.DateTimeField(help_text='vidra ingested', null=True),
        ),
    ]
