# Generated by Django 5.2.6 on 2025-10-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_edgeware_expired_edgeware_offer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeware',
            name='mtcms_prod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edgeware',
            name='mtcms_stag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='edgeware',
            name='expired',
            field=models.DateTimeField(help_text='mtcms expired offer', null=True),
        ),
    ]
