# Generated by Django 5.2.6 on 2025-10-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_edgeware_mtcms_prod_edgeware_mtcms_stag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeware',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.provider'),
        ),
    ]
