# Generated by Django 5.2.6 on 2025-10-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_provider_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edgeware',
            name='stream_url',
        ),
    ]
