# Generated by Django 5.2.6 on 2025-10-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_edgeware_stream_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edgeware',
            old_name='api_loaded',
            new_name='ew_dump_loaded',
        ),
    ]
