# Generated by Django 5.2.6 on 2025-10-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_rename_api_loaded_edgeware_ew_dump_loaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='file',
            field=models.FilePathField(match='.*tar', max_length=512, path='/export/isilj/fenix2', recursive=True, unique=True),
        ),
    ]
