# Generated by Django 5.2.6 on 2025-10-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_packet_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
