# Generated by Django 5.2.6 on 2025-11-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_packet_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='storages',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
