# Generated by Django 5.2.6 on 2025-11-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_provider_storages_delete_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logharvest',
            name='flower',
        ),
        migrations.DeleteModel(
            name='Plugin',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='created',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='modified',
        ),
        migrations.DeleteModel(
            name='LogHarvest',
        ),
    ]
