# Generated by Django 5.2.8 on 2025-11-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0021_remove_logharvest_flower_delete_plugin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredEdgeware',
            fields=[],
            options={
                'ordering': ['expired'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard.edgeware',),
        ),

        migrations.CreateModel(
            name='SFTPGoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event',
                 models.CharField(db_index=True, help_text='upload, download, delete, rename, etc.', max_length=50)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('uid', models.CharField(blank=True, help_text='SFTPGo internal user ID', max_length=100, null=True)),
                ('protocol', models.CharField(max_length=20)),
                ('path', models.TextField(help_text='Full filesystem path on the server')),
                ('virtual_path', models.TextField(help_text='Path as seen by the user')),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('object_name', models.TextField(blank=True, help_text='Usually the filename', null=True)),
                ('object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Success'), (2, 'Error')], db_index=True)),
                ('timestamp', models.BigIntegerField(help_text='SFTPGo nanosecond timestamp (Unix epoch * 1e9 + ns)')),
                ('date', models.DateTimeField(db_index=True, help_text='Human-readable ISO datetime from SFTPGo')),
                ('elapsed',
                 models.PositiveIntegerField(blank=True, help_text='Operation time in milliseconds', null=True)),
                ('object_data', models.JSONField(blank=True, default=dict,
                                                 help_text='Extra object data (user/folder JSON when applicable)')),
                ('error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'SFTPGo Event',
                'verbose_name_plural': 'SFTPGo Events',
                'ordering': ['-date'],
                'indexes': [
                    models.Index(fields=['username', 'event'], name='dashboard_s_usernam_f42b7f_idx'),
                    models.Index(fields=['date'], name='dashboard_s_date_6d7e18_idx'),
                    models.Index(fields=['protocol'], name='dashboard_s_protoco_a5c45a_idx'),
                ],
            },
        ),
        migrations.DeleteModel(
            name='IngestNotification',
        ),
    ]
