# Generated by Django 5.2.8 on 2025-11-25 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_expirededgeware_edgeware_tags_sftpgoevent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atemejob',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='atemejob',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='atemejobevent',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='atemejobevent',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='packet',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='packet',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='vidrajob',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='vidrajob',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
