FROM python:3.13
# FROM python:3.13-slim

# Set environment variables to avoid Python buffering and ensure UTF-8
ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

# Optional: install system dependencies (if needed)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set your Devpi server URL (replace with yours)
ARG DEVPI_URL=https://pypi-paytv.telekom.si/rkambic/stable

# Optionally, credentials can be passed as build arguments (not secure if pushed to logs)
ARG DEVPI_USER
ARG DEVPI_PASS

# Create .pip/pip.conf with Devpi URL and credentials (basic auth)
RUN mkdir -p /root/.pip 
COPY pip.conf /root/.pip/pip.conf

# Copy your code and install dependencies
WORKDIR /app
RUN pip3 install "https://pypi-paytv.telekom.si/rkambic/stable/+f/c56/fcf744b69bcde/vidra_kit-0.1.0-py3-none-any.whl#sha256=c56fcf744b69bcde74358e515bbb02a2dc463292072fb7dc6ed2c45a78684de1"
# RUN pip install vidra-kit

# Copy rest of app

CMD ["vidra-kit", "ingest", "worker"]