# Generated by Django 5.2.8 on 2025-11-27 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filenode_delete_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filenode',
            options={'ordering': ['is_folder', 'name'], 'verbose_name': 'File / Folder', 'verbose_name_plural': 'File System Tree'},
        ),
        migrations.AddField(
            model_name='filenode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filenode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='filenode',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='In bytes', null=True),
        ),
        migrations.AlterField(
            model_name='filenode',
            name='is_folder',
            field=models.BooleanField(default=False, verbose_name='Is Folder'),
        ),
    ]
