# Generated by Django 5.2.8 on 2025-11-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_filenode_options_filenode_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filenode',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, help_text='In bytes', null=True),
        ),
    ]
