# Generated by Django 5.2.6 on 2025-09-20 22:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.SlugField(max_length=255, verbose_name="name")),
                (
                    "order_number",
                    models.SmallIntegerField(default=0, verbose_name="order number"),
                ),
                ("condition", models.JSONField(default=dict, verbose_name="condition")),
            ],
            options={
                "verbose_name": "Audio profile",
                "verbose_name_plural": "Audio profiles",
                "ordering": ["order_number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AudioTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.SlugField(max_length=255, verbose_name="name")),
                ("params", models.JSONField(default=dict, verbose_name="params")),
            ],
            options={
                "verbose_name": "Audio track",
                "verbose_name_plural": "Audio tracks",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Preset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.SlugField(max_length=255, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "Preset",
                "verbose_name_plural": "Presets",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AudioProfileTracks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.SmallIntegerField(default=0, verbose_name="order number"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_transcoding.audioprofile",
                        verbose_name="profile",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_transcoding.audiotrack",
                        verbose_name="track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio profile track",
                "verbose_name_plural": "Audio profile tracks",
                "ordering": ["order_number"],
                "abstract": False,
                "unique_together": {("profile", "track")},
            },
        ),
        migrations.AddField(
            model_name="audioprofile",
            name="audio",
            field=models.ManyToManyField(
                through="video_transcoding.AudioProfileTracks",
                to="video_transcoding.audiotrack",
                verbose_name="Audio tracks",
            ),
        ),
        migrations.AddField(
            model_name="audiotrack",
            name="preset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_tracks",
                to="video_transcoding.preset",
                verbose_name="preset",
            ),
        ),
        migrations.AddField(
            model_name="audioprofile",
            name="preset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_profiles",
                to="video_transcoding.preset",
                verbose_name="preset",
            ),
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "new"),
                            (1, "queued"),
                            (2, "process"),
                            (3, "done"),
                            (4, "error"),
                        ],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, null=True, verbose_name="Error"),
                ),
                (
                    "task_id",
                    models.UUIDField(blank=True, null=True, verbose_name="Task ID"),
                ),
                (
                    "source",
                    models.URLField(
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=("ftp", "http", "https")
                            )
                        ],
                        verbose_name="Source",
                    ),
                ),
                (
                    "basename",
                    models.UUIDField(blank=True, null=True, verbose_name="Basename"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, null=True, verbose_name="metadata"),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="duration"
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="video_transcoding.preset",
                        verbose_name="preset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Video",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VideoProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.SlugField(max_length=255, verbose_name="name")),
                (
                    "order_number",
                    models.SmallIntegerField(default=0, verbose_name="order number"),
                ),
                ("condition", models.JSONField(default=dict, verbose_name="condition")),
                (
                    "segment_duration",
                    models.DurationField(verbose_name="segment duration"),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_profiles",
                        to="video_transcoding.preset",
                        verbose_name="preset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video profile",
                "verbose_name_plural": "Video profiles",
                "ordering": ["order_number"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VideoTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.SlugField(max_length=255, verbose_name="name")),
                ("params", models.JSONField(default=dict, verbose_name="params")),
                (
                    "preset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_tracks",
                        to="video_transcoding.preset",
                        verbose_name="preset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video track",
                "verbose_name_plural": "Video tracks",
                "abstract": False,
                "unique_together": {("name", "preset")},
            },
        ),
        migrations.CreateModel(
            name="VideoProfileTracks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.SmallIntegerField(default=0, verbose_name="order number"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_transcoding.videoprofile",
                        verbose_name="profile",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video_transcoding.videotrack",
                        verbose_name="track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video profile track",
                "verbose_name_plural": "Video profile tracks",
                "ordering": ["order_number"],
                "abstract": False,
                "unique_together": {("profile", "track")},
            },
        ),
        migrations.AddField(
            model_name="videoprofile",
            name="video",
            field=models.ManyToManyField(
                through="video_transcoding.VideoProfileTracks",
                to="video_transcoding.videotrack",
                verbose_name="Video tracks",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="audiotrack",
            unique_together={("name", "preset")},
        ),
        migrations.AlterUniqueTogether(
            name="audioprofile",
            unique_together={("name", "preset")},
        ),
        migrations.AlterUniqueTogether(
            name="videoprofile",
            unique_together={("name", "preset")},
        ),
    ]
