# Generated by Django 5.2.8 on 2025-11-25 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_package', models.FileField(upload_to='packages/')),
                ('mezzanine_video', models.FileField(blank=True, upload_to='mezzanine/')),
                ('hevc_archive', models.FileField(blank=True, upload_to='archive/hevc/')),
                ('dash_directory', models.CharField(blank=True, max_length=255)),
                (
                    'status',
                    models.CharField(
                        choices=[('uploaded', 'Uploaded'), ('adi_validated', 'ADI Validated'), ('processing', 'Processing'), ('ready', 'Ready'), ('rejected', 'Rejected'), ('error', 'Error')],
                        default='uploaded',
                        max_length=20,
                    ),
                ),
                ('processing_log', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
