# Generated by Django 5.2.8 on 2025-11-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0002_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('vidra_task', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('queue', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='package',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
