# Generated by Django 5.2.8 on 2025-11-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0003_provider_rename_created_package_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='manifest',
            field=models.FileField(blank=True, null=True, upload_to='manifests/'),
        ),
    ]
