# Generated by Django 5.2.8 on 2025-11-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0004_package_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='adi_xml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
