# Generated by Django 5.2.8 on 2025-11-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0005_package_adi_xml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='adi_xml',
        ),
        migrations.AlterField(
            model_name='provider',
            name='queue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='vidra_task',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('name', 'vidra_task', 'queue'), name='unique_provider_task'),
        ),
    ]
