# Generated by Django 5.2.8 on 2025-11-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0006_remove_package_adi_xml_alter_provider_queue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='original_package',
            field=models.FileField(blank=True, upload_to='packages/'),
        ),
    ]
