# Generated by Django 5.2.8 on 2025-11-28 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0007_video_modified_at_alter_video_original_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('creation_time', models.DateTimeField(null=True)),
                ('modification_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('error', 'ERROR'), ('done', 'SUCCESS')], max_length=10, null=True)),
                ('playable', models.BooleanField(default=False)),
                ('content_duration_ms', models.IntegerField(null=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vod.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_protocol', models.CharField(choices=[('hls', 'hls'), ('dash', 'dash'), ('mss', 'mss')], max_length=4)),
                ('uri', models.URLField(max_length=512)),
                ('edge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vod.edge')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('edge', 'stream_protocol'), name='unq_edge_proto')],
            },
        ),
    ]
