# Generated by Django 5.2.8 on 2025-11-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0008_edge_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='content_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
