# Generated by Django 5.2.6 on 2025-10-24 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_page_tinymcemedia'),
        ('users', '0003_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='for not logged in users', max_length=33, null=True)),
                ('action', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('watch', 'Watch'), ('report', 'Report'), ('rate', 'Rate')], default='watch', max_length=20)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('remote_ip', models.CharField(blank=True, max_length=40, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediaactions', to='files.media')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useractions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['user', 'action', '-action_date'], name='users_media_user_id_243dca_idx'),
                    models.Index(fields=['session_key', 'action'], name='users_media_session_f28db3_idx'),
                ],
            },
        ),
    ]
