# Generated by Django 5.2.8 on 2025-11-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_page_tinymcemedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtitle',
            options={'ordering': ['language__title'], 'verbose_name': 'Caption', 'verbose_name_plural': 'Captions'},
        ),
        migrations.AlterModelOptions(
            name='transcriptionrequest',
            options={'verbose_name': 'Caption Request', 'verbose_name_plural': 'Caption Requests'},
        ),
        migrations.AlterModelOptions(
            name='videotrimrequest',
            options={'verbose_name': 'Trim Request', 'verbose_name_plural': 'Trim Requests'},
        ),
    ]
