# Generated by Django 5.2.8 on 2025-11-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_alter_subtitle_options_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='category',
        #     name='identity_provider',
        # ),
    ]
